In [2]:
import numpy as np

In [3]:
from kaggle_environments import make
env = make("connectx")
print(env.name, env.version)
print("Default Agents: ", *env.agents)

Loading environment lux_ai_s2 failed: No module named 'vec_noise'
connectx 1.0.1
Default Agents:  random negamax


In [4]:
env = make("connectx", debug=True)

# Training agent in first position (player 1) against the default random agent.
trainer = env.train([None, "random"])

obs = trainer.reset()
for _ in range(2):
    action = 0 # Action for the agent being trained.
    #env.render(mode="ipython", width=600, height=500, header=False)
    obs, reward, done, info = trainer.step(action)
    print(np.reshape(obs["board"], (6,7)))
    if done:
        obs = trainer.reset()
        

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 2 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 2 0 2 0 0]]


In [5]:
observation_space = gym.spaces.Discrete

Help on Environment in module kaggle_environments.core object:

class Environment(builtins.object)
 |  Environment(specification=None, configuration=None, info=None, steps=None, logs=None, agents=None, interpreter=None, renderer=None, html_renderer=None, debug=False, state=None)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, specification=None, configuration=None, info=None, steps=None, logs=None, agents=None, interpreter=None, renderer=None, html_renderer=None, debug=False, state=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  clone(self)
 |      Returns:
 |          Environment: A copy of the current environment.
 |  
 |  debug_print(self, message)
 |  
 |  play(self, agents=None, **kwargs)
 |      Renders a visual representation of the environment and allows interactive action selection.
 |      
 |      Args:
 |          **kwargs (dict): Args directly passed into render().  Mode is fixed to ipython.
 |      
 |      Returns:
 |         

In [6]:
help(make)

Help on function make in module kaggle_environments.core:

make(environment, configuration=None, info=None, steps=None, logs=None, debug=False, state=None)
    Creates an instance of an Environment.
    
    Args:
        environment (str|Environment):
        configuration (dict, optional):
        info (dict, optional):
        steps (list, optional):
        debug (bool=False, optional): Render print() statments to stdout
        state (optional):
    
    Returns:
        Environment: Instance of a specific environment.

